### ISSUE TITLE
Meta: update contributions license

### ISSUE THREAD

**Issue by akhmerov** [topocm/topocm_content#86]
Right now we're using CC-BY-SA-NC 4.0 Int, which is [problematic](https://en.wikipedia.org/wiki/Creative_Commons#Criticism_of_the_non-commercial_license). We should try to remove the -NC clause.

TODO list:
- [x] Decide between CC-BY-SA vs CC-BY
- [x] Coordinate with the Delft extension school
- [ ] Acquire relicensing permission of the external contributions copyright holders.
  - [x] Carlo Beenakker
  - [x] Yuval Oreg
  - [x] Bernard van Heck
  - [x] Dganit Meidan
  - [x] Ady Stern
  - [x] Bertrand Halperin
  - [x] Xiaoliang Qi
  - [x] Duncan Haldane
  - [x] Charles Kane
  - [x] Michael Wimmer
  - [x] Joel Moore
  - [x] David Vanderbilt
  - [x] Taylor Hughes
  - [ ] Shinsei Ryu
  - [x] Fabian Hassler
  - [x] Piet Brouwer
  - [ ] Alex Altland
  - [ ] Ashvin Vishwanath
  - [x] Vincenzo Vitelli
  - [ ] Mark Rudner
  - [x] Liang Fu
  - [ ] Sankar Das Sarma
  - [x] Barbara Terhal
  - [ ] Zahid Hasan (data)
  - [x] JPSJ (data)
- [x] Update the license.

**Comment by akhmerov** [comment]
Update: added list of contributors holding copyright to parts of content.

**Comment by akhmerov** [comment]
Update: for the videos I suggest to use CC-BY, since youtube doesn't support CC-BY-SA.
